.github/workflows/ci.yml
src/backend/mac/application.rs
src/backend/mac/window.rs

Apply clippy suggestions for the macOS backend, so that CI does not fail.

Apply macOS clippy suggestion.

---

Cargo.toml
src/backend/x11/application.rs
src/backend/x11/window.rs

- make x11 backend default because gtk backend does not support raw-window-handle
- remove custom cursors (needs piet)

unpiet x11 backend

---

Cargo.toml

This syncs with peniko and gives us the new GAT stuff.

Update kurbo dependency to 0.9.0

---

src/backend/windows/window.rs

Fix scaling of get_size on Windows

---

src/backend/mac/window.rs

We were setting ns_view but not ns_window, which was causing the query to fetch scale to fail, and thus dpi wrong.
I'm not 100% sure we should be calling the `window` method to get this, we could store the NSWindow pointer in the WindowHandle. The main reason we didn't do this was to support the VST use case, but that's not actively being developed.
In any case, I think this is probably "good enough."

Initialize ns_window on mac

---

Cargo.toml
examples/shello.rs

This also fixes a lost device issue in the `shello` example.

Update to use renamed vello crate

---

build.rs
src/backend/mac/window.rs
src/backend/windows/window.rs

It seems like maybe the clippy lints changed with the most recent rust version; the build of my other pull requests is failing. This small change seems to make clippy happy again.

Fix clippy warnings

---

src/backend/windows/window.rs

After this change, was able to successfully run the wgpu example added in #53.

Fix build on aarch64 windows targets

---

CHANGELOG.md
Cargo.toml
README.md
examples/wgpu-triangle/main.rs
examples/wgpu-triangle/shader.wgsl

Combines together the [wgpu triangle example](https://github.com/gfx-rs/wgpu/blob/v0.14.2/wgpu/examples/hello-triangle/main.rs) and the shello example to demonstrate wgpu working with glazier.
Tested on macos and windows.

Add wgpu triangle example

---

src/backend/x11/application.rs
src/backend/x11/window.rs

This PR receives Xserver ` LeaveNotify` events and passes them to Glazier's `mouse_leave`, required to fix linebender/xilem#13 when Glazier's x11 backend is selected.

Handle mouse_leave

---

src/backend/x11/application.rs
src/backend/x11/clipboard.rs
src/backend/x11/screen.rs
src/backend/x11/util.rs
src/backend/x11/window.rs

All other `Application` objects are cheap to clone. The X11 one had quite a lot of fields.
This probably doesn't have a big impact anywhere; it was on the path to trying to fix another bug...

X11: make clone cheap

---

src/window.rs

I assume this changed at some point, but whoever made the methods mut didn't update this comment?

Remove note about non-mut WinHandler methods now that methods take mut

---

Cargo.toml

This mirrors the current patch as it exists in the [vello](https://github.com/linebender/vello/blob/dfde0936e5064ac8bb2765e1c3fdc1d5ac757a83/Cargo.toml) `Cargo.toml`.
Without this change, I get a shader error on `aarch64-apple-darwin`:
```
thread 'main' panicked at 'wgpu error: Validation Error
Caused by:
In Device::create_compute_pipeline
Internal error: Metal: program_source:460:29: warning: unused variable '_e379'
int _e379 = uint(tile_ix) < 1 + (_buffer_sizes.size6 - 0 - 8) / 8 ? metal::atomic_fetch_add_explicit(&tiles[tile_ix].backdrop, backdrop, metal::memory_order_relaxed) : DefaultConstructible();
^
program_source:513:70: error: cannot take the address of an rvalue of type 'metal::uint' (aka 'unsigned int')
uint _e450 = metal::atomic_exchange_explicit(&uint(tile_ix_1) < 1 + …
```

Add naga patch to Cargo.toml

---

src/backend/mac/text_input.rs
src/text.rs

Fixes #8. Unfortunately it's not trivial to test this. I plan to restore the `edit_text.rs` example soon so that we have a working IME example we can use to make sure everything here is still working.
(Also definitely let me know if this flood of tiny PRs is getting annoying and I should stop, or if there's some other way I can be more helpful!)

Restore hit_test_point method on InputHandler

---

src/backend/gtk/clipboard.rs
src/backend/gtk/dialog.rs
src/backend/gtk/menu.rs
src/backend/gtk/screen.rs
src/backend/gtk/window.rs

Fix #47
The code to create Piet context is removed. And `make_cursor` requires types from piet too, so I commented it out with TODO mentioning it.
shello example isn't working because it needs raw handles, but we can obtain it from GdkX11 and GdkWayland (there's no crate yet).

Fix build on gtk feature

---

Cargo.toml
src/backend/gtk/dialog.rs
src/backend/gtk/error.rs
src/backend/wayland/application.rs
src/backend/wayland/error.rs
src/backend/wayland/keyboard.rs
src/backend/wayland/surfaces/buffers.rs
src/backend/windows/error.rs
src/backend/windows/mod.rs
src/backend/x11/application.rs
src/backend/x11/dialog.rs
src/backend/x11/mod.rs
src/backend/x11/pointer.rs
src/backend/x11/util.rs
src/backend/x11/window.rs

This will eventually let us support pointer events, but for now the only benefit is that it supports sub-pixel resolution on input devices that report it.
I've also bumped vello, because for some reason the old one was failing to compile with some missing peniko variants. I'm not sure how that slipped by, given that we're pinning the git revs now...

[x11] Switch mouse events from the core protocol to xinput.

---

Cargo.toml
examples/accesskit.rs

glazier proper only requires version bumps, but the example needed to be updated for the breaking API changes. (xilem will need to be updated as well.)

Update for the AccessKit node refactor

---

src/backend/x11/pointer.rs

For pointer events, we'll eventually want to listen to all pointers. For now, listening to only master pointers fixes duplicate events.
Fixes #73

[x11] Only listen to master pointers

---

src/backend/windows/window.rs

Clippy lints addressed:
* [`derivable_impls`](https://rust-lang.github.io/rust-clippy/master/index.html#derivable_impls)

Satisfy clippy 1.68.

---

examples/edit_text.rs
src/text.rs

It's pretty slow and the code is kind of crappy, but I think it's good enough for review. Having a text editing example is I think important to make sure our text editing APIs don't degrade.
Chinese text input no longer shows the composition window; still have to look into why that is, but perhaps I can fix that in another PR.

Add edit text example

---

AUTHORS

Fixes #6 
I've chosen to just copy the AUTHORS file rather than looking at git blame output --- this list is quite short, and it seems better for copyright purposes to include an extra name unnecessarily than remove a name that should have been there.

Copy AUTHORS from druid

---

examples/accesskit.rs
examples/edit_text.rs
examples/shello.rs
examples/wgpu-triangle/main.rs
src/backend/gtk/window.rs
src/backend/mac/window.rs
src/backend/wayland/window.rs
src/backend/web/window.rs
src/backend/windows/window.rs
src/backend/x11/window.rs
src/window.rs

Following up on [the discussion in Zulip](https://xi.zulipchat.com/#narrow/stream/351333-glazier/topic/Builder.20pattern.20in.20WindowBuilder), this PR changes `WindowBuilder` methods `&mut self` argument to `mut self` and return value to `Self`, so that methods could be chained. Besides that, I took a liberty to also remove `set_` prefix from `WindowBuilder` methods, and also changed `WindowBuilder` for all backends to keep it consistent with the top-level one. Let me know if any of that is undesired, I'll revert.
I've tested all examples except `accesskit` on X11 backend, and tested their compilation on Wayland and GTK backends (I have issues running on these backends same as on `main`: GTK segfaults, Wayland has transparent window). I hope the CI will make sure others compile?

Change WindowBuilder to a more conventional builder pattern

---

examples/edit_text.rs
examples/shello.rs
examples/wgpu-triangle/main.rs
src/backend/mac/window.rs

Fixes #64
This change allows the view object to speak the CALayerDelegate protocol, and automatically installs it as its own layer delegate if the view becomes layer-backed.
We also update the `invalidate` function to defer its `setNeedsLayer` call to prevent infinite loops when `invalidate` is called within a `WinHandler::paint()` implementation. `request_anim_frame` and `invalidate` now both have the same implementation; as far as I'm aware, the behavior wasn't actually different on macOS.
To test that this works, I removed the idle callback hack from both examples and saw both work correctly on macOS Monterey.

Automatically register macos CALayer delegate

---

Cargo.toml
build.rs

While playing with xilem I noticed long download and compile times. One cause is that glazier enables x11 by default and xilem does so too. Currently, bindgen will be compiled even on platforms not needing bindings, which adds at least 10 seconds to the build times.

Only compile bindgen on platforms actually generating bindings

---

src/lib.rs

Previously, the type name was inaccessible and could not be used as e.g. a field in a struct.

Re-export `AppHandle` from the crate root.

---

.gitignore
examples/edit_text.rs
src/backend/shared/xkb/keycodes.rs
src/backend/shared/xkb/mod.rs
src/backend/wayland/keyboard.rs
src/backend/x11/application.rs

This addresses the issue being ran into in https://github.com/linebender/druid/pull/2057 and in [#glazier > Keyboard Shortcuts](https://xi.zulipchat.com/#narrow/stream/351333-glazier/topic/Keyboard.20shortcuts).
This allows keyboard shortcuts to be used properly, at least on the x11 backend. I can't get the wayland backend to run on my machine - it instantly segfaults in wgpu-triangle, and displays nothing in edit-text.

Handle keyboard input more robustly on linux

---

src/scale.rs

The Druid book URL structure has changed since Glazier was forked. This PR fixes the broken link.

Fix broken link.

---

src/backend/linux/application.rs
src/backend/linux/clipboard.rs
src/backend/linux/error.rs
src/backend/linux/menu.rs
src/backend/linux/mod.rs
src/backend/linux/screen.rs
src/backend/linux/window.rs
src/backend/mod.rs
src/backend/shared/xkb/mod.rs
src/backend/wayland/window.rs
src/backend/x11/application.rs
src/backend/x11/screen.rs
src/backend/x11/window.rs
src/platform/linux.rs
src/window.rs

This allows running with both the x11 feature and the wayland feature at the same time.
I've left the X11 feature as default, because the wayland backend doesn't current render (which needs debugging)
See also [#glazier > Linux "multiplexing"](https://xi.zulipchat.com/#narrow/stream/351333-glazier/topic/Linux.20.22multiplexing.22)

Multiplex Linux backends

---

CHANGELOG.md
Cargo.toml

This paves the way for updating it within Xilem as well (once that also updates to a current Glazier).

Update AccessKit to 0.11 from 0.9.

---

CHANGELOG.md
src/lib.rs
src/pointer.rs

These are used in the `pub` enum `PointerType`, so they were implicitly `pub`, but not included in the generated docs.

Export `MouseInfo`, `PenInfo`, `TouchInfo` structs.

---

.github/workflows/ci.yml

As discussed back in March (#76 + office hours) we are pinning to an explicit Rust toolchain version that we manually update.
This PR makes that workflow easier by making it a single variable and also adds a comment so that anyone looking to modify the CI workflow file knows what's the strategy.
This PR also adds the merge queue trigger to then later enable merge queues, which is also part of the strategy.

Describe the CI Rust toolchain strategy in the workflow file.

---

src/backend/windows/window.rs

Interestingly, this happens with 1.71 and nightly. It does not happen with 1.70 or earlier.
Compilation confirmed to work with 1.65 (MSRV for Kurbo).

Fix unused mut warning.

---

.github/workflows/ci.yml

Move to Rust 1.71in CI

---

src/backend/mac/keyboard.rs
src/backend/mac/util.rs
src/backend/mac/window.rs
src/backend/windows/window.rs
src/clipboard.rs
src/common_util.rs
src/hotkey.rs
src/menu.rs
src/mouse.rs
src/pointer.rs
src/scale.rs
src/screen.rs
src/window.rs

This fixes some typos and formatting. It also changes to using intra-doc-links rather than links to the rustdoc-generated HTML.

Doc tweaks and improvements.

---

src/window.rs

impl `fmt::Debug` for `WindowLevel`.

---

src/backend/mac/window.rs
src/backend/web/window.rs
src/backend/windows/window.rs
src/backend/x11/window.rs
src/mouse.rs
src/pointer.rs

As described in issue #88, the web specifications that we are tracking refer to the mouse buttons as primary/secondary/auxillary rather than left/right/middle.
Fixes #88.

Rename `MouseButton`/`PointerButton` variants.

---

src/backend/mac/window.rs
src/backend/windows/window.rs

This is a draft as I think it is something people may want to comment on.
It is currently only on Windows, but I'll probably push a commit with Mac support soon (within the next day or three).
It doesn't do any extra features yet like multiple pointers. That requires using the raw input API on Windows, I think. (But that can happen separately.)
Once #126 lands (or is rejected), I'll update this via rebase to remove the extra stuff from here.
There's interesting questions once multiple pointers are supported, like how the capturing code should handle that.
I don't have any fancy Windows input devices.

Pointer Events

---

examples/pen.rs
examples/shello.rs
src/backend/mac/window.rs
src/backend/web/window.rs
src/backend/windows/window.rs
src/backend/x11/window.rs
src/window.rs

This makes it match `KeyboardEvent`.

Pass `PointerEvent`/`MouseEvent` by value, not ref.

---

src/backend/mac/menu.rs
src/backend/windows/keyboard.rs
src/backend/windows/menu.rs
src/backend/windows/window.rs
src/backend/x11/window.rs
src/hotkey.rs
src/keyboard.rs
src/lib.rs
src/text.rs

This was being wrapped to add a small number of extension methods which can be added via a trait instead.
The resulting code is smaller and makes it clear what is different from the upstream `keyboard_types::Modifiers`.

Stop wrapping keyboard_types::Modifiers.

---

README.md

I just did a fresh Ubuntu 23.04 install and was greeted with the following error when attempting to build with the `wayland` feature:
```
error: failed to run custom build command for `wayland-sys v0.30.1`
Caused by:
process didn't exit successfully: `/home/strom/Rust/glazier/target/debug/build/wayland-sys-23ce904e0e81cf94/build-script-build` (exit status: 101)
--- stdout
cargo:rerun-if-env-changed=WAYLAND_CLIENT_NO_PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG
cargo:rerun-if-env-changed=WAYLAND_CLIENT_STATIC
cargo:rerun-if-env-changed=WAYLAND_CLIENT_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC …
```

Add Wayland dev package dependency info to `README.md`.

---

src/pointer.rs

The old `MouseButtons` bitset had funky off-by-one storage. The new `PointerButtons` has more intuitive straight storage. This PR updates the debug formatter to match that new reality.
Easy way to test is with the `shello` example and clicking the primary mouse button. Without this PR it will print all zeroes, with this PR applied it will print correctly.

Fix `PointerButtons` debug formatter.

---

src/backend/web/window.rs

All other backends and more importantly the cross-platform `WindowHandle::set_title` method takes the title as a `&str`. The web backend ends up using a `&str` too, so the inbetween `String` allocation doesn't make much sense. This PR removes that.

Match the web backend's `set_title` method signature to others.

---

Cargo.toml
examples/common/mod.rs
examples/common/text.rs
examples/edit_text.rs
examples/pen.rs
examples/shello.rs

Vello has moved on to `wgpu` 0.17 and different font handling. This PR brings all of that to the Glazier examples.

Migrate to the latest `vello` version.

---

Cargo.toml

Only wayland code is using `calloop` now and it uses it as a re-export rather than this version here.

deps: Remove direct calloop dep.

---

.github/workflows/ci.yml
Cargo.toml
examples/edit_text.rs
examples/pen.rs
examples/shello.rs
examples/wgpu-triangle/main.rs

As has been noted in #1 the `glazier` CI has been mostly a rough port of the `druid-shell` CI script. Recently, mostly thanks to @waywardmonkeys, our CI scripts have received some improvements. This PR here pushes that forward some more by incorporating some `druid-shell` post-fork changes and also a few other lessons from running the Druid CI over the years.
* The script now has a short name, `CI`, instead of the automatic `.github/workflows/ci.yml` to reduce UI noise.
* Everything is more generic, which means the script has e.g. `--workspace` which has no practical effect for Glazier at this point in time. The goal is to have a more easily syncable generic Linebender CI with minimal required changes per repository.
* Wayland no longer receives a separate job and instead gets tested …

Make the CI script more generic and robust.

---

examples/edit_text.rs
src/backend/wayland/application.rs
src/backend/wayland/window.rs

This was luckily really simple.
I've also added support for a blinking cursor to the edit_text example, to test out this functionality.
Reporting when/how to blink the cursor is a bit of an open question at the moment - it could even be the responsibility of the IME (via the input lock system?). But that can be improved later

Support timers on Wayland

---

Cargo.toml

For some reason, this passed CI but is actually broken and needs `winerror` feature enabled. This was previously transitively enabled by `dwrite` and probably other features, but we removed the `dwrite` feature.

Fix Windows build.

---

.github/workflows/ci.yml
Cargo.toml

We ran into an interesting situation with #151 where the CI succeeded despite our `Cargo.toml` not correctly specifying the `winerror` feature for `winapi`. --- ( _`Cargo.toml` was fixed by #153._ )
This happened because some of our dev dependencies enable the `winerror` feature of `winapi`. This can be seen by comparing `cargo tree -e features` vs `cargo tree -e features -e no-dev`.
Looking deeper, this happened because `cargo` builds with dev dependencies if any of `--tests` / `--benches` / `--examples` are enabled. This was always the case for us, as we either did `cargo test` or `cargo clippy --all-targets`.
This issue has bitten us before too, just this year. Back in April we received a bug report for Druid ([druid#2373](https://github.com/linebender/druid/issues/2373)) that a simple …

Split CI `clippy` into main & auxiliary steps.

---

Cargo.toml
src/backend/mac/menu.rs
src/backend/windows/keyboard.rs
src/backend/windows/menu.rs
src/backend/windows/window.rs
src/backend/x11/window.rs
src/hotkey.rs
src/keyboard.rs
src/lib.rs
src/text.rs

This lets us remove our `ModifiersExt` now that that functionality is available in the upstream release.

deps: Update `keyboard-types` to 0.7.

---

Cargo.toml

windows: Fix not linking against shell32 lib.

---

Cargo.toml

This only enabled `serde` within `kurbo`, but this crate doesn't actually use `serde` at all.
If a dependant crate wants `serde` enabled in `kurbo`, they would already be using `kurbo` and can enable it on their own.
This was added in 080a094b1e70bd7a6194522b3d336e8c9a91e7ee but with no indication in the commit as to why it was needed. This was in 2021, so it pre-dates the `glazier` efforts.

Remove `serde` feature.

---

Cargo.toml
src/backend/wayland/window.rs

This should resolve an issue Lapce is having on the Wayland backend. There is an unexplained hang I've discovered, but the workaround I've also implemented is a correctness improvement which incidentally appears to address that hang?
See [#glazier > Freeze with Wayland egl](https://xi.zulipchat.com/#narrow/stream/351333-glazier/topic/Freeze.20with.20Wayland.20egl).
I've also disabled the wayland backend by default again, as it was inadvertently enabled in #119. I would like us to expose the Wayland feature up the stack all the way to Lapce (cc @waywardmonkeys), so that testing can occur directly on main Lapce without patches

Wayland: connect in configure

---

examples/edit_text.rs

This fixes a future clippy warning.

edit_text: apply_movement doesn't need mut edit_lock.

---

src/backend/windows/window.rs

The `Cursor` isn't `Send` / `Sync`, so this can just use `Rc`.
Since `HCURSOR` isn't `Send` / `Sync`, it wasn't valid to use `Arc` with it. This generates a clippy warning starting in Rust 1.72.
Fixes #138.

windows: Use `Rc` with `HCURSOR`.

---

.github/workflows/ci.yml

This PR moves the CI to Rust 1.72.

Bump Rust stable to 1.72.

---

examples/accesskit.rs
examples/edit_text.rs
examples/pen.rs
examples/shello.rs
src/backend/mac/window.rs
src/backend/wayland/input/mod.rs
src/backend/web/window.rs
src/backend/windows/window.rs
src/backend/x11/window.rs
src/text.rs
src/window.rs

This reverts #129 (87b132c) which had changed `PointerEvent` to pass by value rather than ref.
Since `KeyboardEvent` has a cost to clone / copy, this may be a better approach.

Pass PointerEvent/ KeyEvent by ref.

---

.github/workflows/ci.yml

Simple maintenance, primary [change](https://github.com/actions/checkout/releases/tag/v4.0.0) is `node` upgrade under the hood.

Upgrade `actions/checkout` to `v4`.

---

.github/workflows/ci.yml
examples/shared_app_handle.rs

Removed the redundant redefinition of `handle` from the `shared_app_handle` example to satisfy Clippy 1.73.

Bump Rust stable toolchain to 1.73.

---

.github/workflows/ci.yml

Clippy didn't need further satisfaction.

Bump Rust stable toolchain to 1.74.

---

Cargo.toml
examples/accesskit.rs
examples/edit_text.rs
examples/pen.rs
examples/shello.rs
examples/wgpu-triangle/main.rs
src/backend/mac/window.rs
src/backend/windows/window.rs

The biggest change in glazier itself is that glazier, rather than the application, is now responsible for telling AccessKit about the focus state of the window, because this is now tracked in the AccessKit platform adapter rather than in the tree itself. Most of the other breaking API changes affected the example.

Update to AccessKit 0.12

---

Cargo.toml
examples/accesskit.rs
examples/common/text.rs
examples/edit_text.rs
examples/pen.rs
examples/shello.rs
examples/wgpu-triangle/main.rs

This also requires bumping vello/wgpu dev-deps and fixing all the examples.

Bump kurbo version
